#!/bin/sh /etc/rc.common
START=70
STOP=89
USE_PROCD=1

start_service() {
	local enabled
	config_load we5927_lte
	config_get_bool enabled main enabled 1
	[ "$enabled" = 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/we5927-lte daemon
	procd_set_param respawn 10 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger we5927_lte network firewall
}
